// <auto-generated />
using System;
using GestionEmploiTemps.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionEmploiTemps.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524010021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Creneau", b =>
                {
                    b.Property<int>("IdCreneau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCreneau"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCreneau");

                    b.ToTable("Creneaux");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEns"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEns");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseigner", b =>
                {
                    b.Property<int>("IdEns")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer");

                    b.Property<int>("EnseignantIdEns")
                        .HasColumnType("integer");

                    b.Property<int>("MatiereIdMatiere")
                        .HasColumnType("integer");

                    b.HasKey("IdEns", "IdMatiere");

                    b.HasIndex("EnseignantIdEns");

                    b.HasIndex("MatiereIdMatiere");

                    b.ToTable("Enseignements");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMatiere");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNiveau"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNiveau");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Parcours", b =>
                {
                    b.Property<int>("IdParcours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParcours"));

                    b.Property<int>("IdNiveau")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdParcours");

                    b.HasIndex("IdNiveau");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeance"));

                    b.Property<int?>("EnseignantIdEns")
                        .HasColumnType("integer");

                    b.Property<int>("IdCreneau")
                        .HasColumnType("integer");

                    b.Property<int>("IdEns")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer");

                    b.Property<int>("IdParcours")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalle")
                        .HasColumnType("integer");

                    b.HasKey("IdSeance");

                    b.HasIndex("EnseignantIdEns");

                    b.HasIndex("IdCreneau");

                    b.HasIndex("IdEns");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdParcours");

                    b.HasIndex("IdSalle");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseigner", b =>
                {
                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", "Enseignant")
                        .WithMany("Enseignements")
                        .HasForeignKey("EnseignantIdEns")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Matiere", "Matiere")
                        .WithMany("Enseignants")
                        .HasForeignKey("MatiereIdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Parcours", b =>
                {
                    b.HasOne("GestionEmploiTemps.API.Models.Niveau", "Niveau")
                        .WithMany("Parcours")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Seance", b =>
                {
                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", null)
                        .WithMany("Seances")
                        .HasForeignKey("EnseignantIdEns");

                    b.HasOne("GestionEmploiTemps.API.Models.Creneau", "Creneau")
                        .WithMany("Seances")
                        .HasForeignKey("IdCreneau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEns")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Matiere", "Matiere")
                        .WithMany("Seances")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Parcours", "Parcours")
                        .WithMany("Seances")
                        .HasForeignKey("IdParcours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creneau");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Parcours");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Creneau", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseignant", b =>
                {
                    b.Navigation("Enseignements");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Matiere", b =>
                {
                    b.Navigation("Enseignants");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Niveau", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Parcours", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Salle", b =>
                {
                    b.Navigation("Seances");
                });
#pragma warning restore 612, 618
        }
    }
}
