// <auto-generated />
using System;
using GestionEmploiTemps.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEmploiTemps.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Creneau", b =>
                {
                    b.Property<int>("IdCreneau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCreneau"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCreneau");

                    b.ToTable("Creneaux");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEns"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEns");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseigner", b =>
                {
                    b.Property<int>("IdEns")
                        .HasColumnType("int");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("int");

                    b.Property<int?>("EnseignantIdEns")
                        .HasColumnType("int");

                    b.Property<int?>("MatiereIdMatiere")
                        .HasColumnType("int");

                    b.HasKey("IdEns", "IdMatiere");

                    b.HasIndex("EnseignantIdEns");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("MatiereIdMatiere");

                    b.ToTable("Enseignements");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMatiere");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNiveau"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNiveau");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Parcours", b =>
                {
                    b.Property<int>("IdParcours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParcours"));

                    b.Property<int>("IdNiveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdParcours");

                    b.HasIndex("IdNiveau");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeance"));

                    b.Property<int?>("EnseignantIdEns")
                        .HasColumnType("int");

                    b.Property<int>("IdCreneau")
                        .HasColumnType("int");

                    b.Property<int>("IdEns")
                        .HasColumnType("int");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("int");

                    b.Property<int>("IdParcours")
                        .HasColumnType("int");

                    b.Property<int>("IdSalle")
                        .HasColumnType("int");

                    b.HasKey("IdSeance");

                    b.HasIndex("EnseignantIdEns");

                    b.HasIndex("IdCreneau");

                    b.HasIndex("IdEns");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdParcours");

                    b.HasIndex("IdSalle");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseigner", b =>
                {
                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", null)
                        .WithMany("Enseignements")
                        .HasForeignKey("EnseignantIdEns");

                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEns")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enseigner_Enseignant");

                    b.HasOne("GestionEmploiTemps.API.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enseigner_Matiere");

                    b.HasOne("GestionEmploiTemps.API.Models.Matiere", null)
                        .WithMany("Enseignants")
                        .HasForeignKey("MatiereIdMatiere");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Parcours", b =>
                {
                    b.HasOne("GestionEmploiTemps.API.Models.Niveau", "Niveau")
                        .WithMany("Parcours")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Seance", b =>
                {
                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", null)
                        .WithMany("Seances")
                        .HasForeignKey("EnseignantIdEns");

                    b.HasOne("GestionEmploiTemps.API.Models.Creneau", "Creneau")
                        .WithMany("Seances")
                        .HasForeignKey("IdCreneau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEns")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Matiere", "Matiere")
                        .WithMany("Seances")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Parcours", "Parcours")
                        .WithMany("Seances")
                        .HasForeignKey("IdParcours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmploiTemps.API.Models.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creneau");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Parcours");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Creneau", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Enseignant", b =>
                {
                    b.Navigation("Enseignements");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Matiere", b =>
                {
                    b.Navigation("Enseignants");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Niveau", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Parcours", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionEmploiTemps.API.Models.Salle", b =>
                {
                    b.Navigation("Seances");
                });
#pragma warning restore 612, 618
        }
    }
}
